gsteps : 1
output_size : 48
dataset: stl10
c_dim : 3
z_dim : 128
df_dim : 64
dsteps: 5
gf_dim : 64
architecture : "sngan"
model : "sinkhorn"
batch_norm : True
with_sn : True
dof_dim : 16
pico: 1
learning_rate: 0.0001
ker_lam: 0.
ker_lam_2: 0.5
k_ratio: 0.01
kernel: 'rbf'
beta1: 0.5
beta2: 0.9
MMD_sdlr_num_test: 1
MMD_sdlr_past_sample: 2
MMD_sdlr_freq: 10000
max_iteration: 200001
clip_grad: False
eps: 200
